In [2]:
print('Assignment Exercise 7')

Assignment Exercise 7


1. Create an array for:

i. f(x)= x2sin(x) + e−2x for x ∈ [0,2] in steps of 0.1

ii.  g(x)=xsinh−1(x)+ln(x)for20equallyspacedpointsin[1,5]

iii.  h(x)=log4(x)forx=[2,4,8,16,...,210]

In [12]:
import numpy as np

x1 = np.arange(0, 2.1, 0.1)
f_x = x1**2 * np.sin(x1) + np.exp(-2*x1)
print("1(a) i. f(x) results:\n", f_x)

1(a) i. f(x) results:
 [1.         0.81972909 0.67826682 0.57540845 0.5116359  0.48773583
 0.5044655  0.56226363 0.66100442 0.79979369 0.97680627 1.18916406
 1.43285424 1.70268691 1.99229153 2.29415079 2.59967063 2.89928457
 3.18259005 3.43851409 3.65550535]


ii. g(x)= x sinh−1(x) + ln(x) for 20 equally spaced points in[1,5]

In [13]:
x2 = np.linspace(1, 5, 20)
g_x = x2 * np.arcsinh(x2) + np.log(x2)
print("\n1(a) ii. g(x) results:\n", g_x)


1(a) ii. g(x) results:
 [ 0.88137359  1.42905386  1.98583297  2.55447824  3.13589739  3.73018597
  4.33707806  4.95615159  5.58692579  6.22890835  6.88161827  7.54459646
  8.21741007  8.89965363  9.59094849 10.29094153 10.99930345 11.715727
 12.43992519 13.17162962]


iii. h(x) = log4(x) for x = [2,4,8,16,...,2^10]

In [14]:
x3 = 2**np.arange(1, 11)
h_x = np.log2(x3) / np.log2(4)
print("\n1(a) iii. h(x) results:\n", h_x)


1(a) iii. h(x) results:
 [0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


(b) If
x= [−1 3 2] ,

A= 
[1 4 0
3 7 5
2 8 −2]

and 

b=
[4
−1
6],

find x·b, xA, Ab and A+bx.

In [15]:
import numpy as np

x = np.array([-1, 3, 2])
A = np.array([[1, 4, 0],
              [3, 7, 5],
              [2, 8, -2]])
b = np.array([[4], [-1], [6]])

x_dot_b = x @b
xA = x @ A
Ab = A @ b
A_plus_bx = A + (b @ x.reshape(1, -1))

print("x * b =", x_dot_b)
print("xA =", xA)
print("Ab =\n", Ab)
print("A + bx =\n", A_plus_bx)

x * b = [5]
xA = [12 33 11]
Ab =
 [[  0]
 [ 35]
 [-12]]
A + bx =
 [[-3 16  8]
 [ 4  4  3]
 [-4 26 10]]


2.Referring to the quantities defined in Q1(b),

a) Create [−1 3 2 4 −1 6] and [−1 3 2 4 −1 6] from b and x

In [16]:
import numpy as np

x = np.array([-1, 3, 2])
b = np.array([[4], [-1], [6]])


mat_1 = np.vstack((x, b.flatten())) 

print("2(a) First Matrix:\n", mat_1)


mat_2 = np.concatenate((x, b.flatten()))
print("\n2(a) Second Array:\n", mat_2)

2(a) First Matrix:
 [[-1  3  2]
 [ 4 -1  6]]

2(a) Second Array:
 [-1  3  2  4 -1  6]


(b)Get the following matrices

[8
7
4],  

 [1 7 −2] , 
 
 [7 5 8 −2] , 
 
 [1 0 2 −2 ],


[2 8 −2
3 7 5
1 4 0],

[0 4 1
5 7 3
−2 8 2],

[0 5 −2
4 7 8
1 3 2],

and

[1 4 0 3 7 5 2 8 −2]

In [17]:
import numpy as np

A = np.array([[1, 4, 0], [3, 7, 5], [2, 8, -2]])


slice1 = A[::-1, 1:2]


slice2 = np.diag(A)


slice3 = A[1:, 1:]


slice4 = A[::2, ::2]

print("Slice 1:\n", slice1)
print("Slice 2:", slice2)
print("Slice 3:\n", slice3)
print("Slice 4:\n", slice4)



Slice 1:
 [[8]
 [7]
 [4]]
Slice 2: [ 1  7 -2]
Slice 3:
 [[ 7  5]
 [ 8 -2]]
Slice 4:
 [[ 1  0]
 [ 2 -2]]


3.Referring to the quantities defined in Q1(b),

(a) find the maximum element of x

In [18]:
import numpy as np


x = np.array([-1, 3, 2])


max_x = np.max(x)

print("3(a) Maximum element of x:")
print(max_x)

3(a) Maximum element of x:
3


(b) find the column sum of A

In [19]:
import numpy as np


A = np.array([[1, 4, 0], 
              [3, 7, 5], 
              [2, 8, -2]])


column_sums = np.sum(A, axis=0)

print("3(b) Column sums of A:")
print(column_sums)

3(b) Column sums of A:
[ 6 19  3]


(c) sort the rows of A in descending order

In [20]:
import numpy as np


A = np.array([[1, 4, 0], 
              [3, 7, 5], 
              [2, 8, -2]])


sorted_A_desc = np.sort(A, axis=1)[:, ::-1]

print("3(c) Rows of A sorted in descending order:")
print(sorted_A_desc)

3(c) Rows of A sorted in descending order:
[[ 4  1  0]
 [ 7  5  3]
 [ 8  2 -2]]


(d) find the mean of all elements in A

In [21]:
import numpy as np


A = np.array([[1, 4, 0], 
              [3, 7, 5], 
              [2, 8, -2]])


mean_A = np.mean(A)

print("3(d) Mean of all elements in A:")
print(mean_A)

3(d) Mean of all elements in A:
3.111111111111111
